const CONNECT_AND_ENTER_CHAT = 'CONNECT_AND_ENTER_CHAT';
const SEND_MESSAGE = 'SEND_MESSAGE';
const RECEIVE_MESSAGE = 'RECEIVE_MESSAGE';

const types =  {
  CONNECT_AND_ENTER_CHAT,
  SEND_MESSAGE,
  RECEIVE_MESSAGE
};

export default types;