const SET_OTHER_USERS = 'SET_OTHER_USERS';
const ADD_OTHER_USER = 'ADD_OTHER_USER';
const REMOVE_OTHER_USER = 'REMOVE_OTHER_USER';
const SET_SELF_USER = 'SET_SELF_USER';
const SET_REQUESTED_SELF_USER = 'SET_REQUESTED_SELF_USER';
const ADD_USER_COLOR = 'ADD_USER_COLOR';
const SET_USER_TO_COLOR = 'SET_USER_TO_COLOR';

const types = {
  SET_OTHER_USERS,
  ADD_OTHER_USER,
  REMOVE_OTHER_USER,
  SET_SELF_USER,
  SET_REQUESTED_SELF_USER,
  ADD_USER_COLOR,
  SET_USER_TO_COLOR,
};

export default types;