const SET_CHAT_EVENTS = 'SET_CHAT_EVENTS';
const ADD_CHAT_EVENT = 'ADD_CHAT_EVENT';
const ADD_MESSAGE_STILL_SENDING = 'ADD_MESSAGE_STILL_SENDING';
const REMOVE_MESSAGE_STILL_SENDING = 'REMOVE_MESSAGE_STILL_SENDING';

const types = {
  SET_CHAT_EVENTS,
  ADD_CHAT_EVENT,
  ADD_MESSAGE_STILL_SENDING,
  REMOVE_MESSAGE_STILL_SENDING,
};

export default types;